pipelines:
  - name: pipeline_affinityGroup_test
    configuration:
      environmentVariables:
        readOnly:
          MY_DIR: "../.."
          MY_MESSAGE: '"Hello World!"'
    steps:
      - name: ag_step_1
        type: Bash
        configuration:
          affinityGroup: together
        execution:
          onExecute:
            - echo "Running " $pipeline_name "|" $step_name >$MY_DIR/myoutput.txt
            - echo $MY_MESSAGE >>$MY_DIR/myoutput.txt
            - pwd
            - cat $MY_DIR/myoutput.txt
      - name: ag_step_2
        type: Bash
        configuration:
          affinityGroup: together
          inputSteps:
             - name: ag_step_1
        execution:
          onExecute:
            - pwd
            - cat $MY_DIR/myoutput.txt
