pipelines:
  - name: pipeline_affinityGroup_test
    configuration:
      environmentVariables:
        readOnly:
          MY_MESSAGE: '"Hello World!"'
    steps:
      - name: ag_step_1
        type: Bash
        configuration:
          runtime:
            type: host        
          affinityGroup: together
        execution:
          onExecute:
            - echo "Running " $pipeline_name "|" $step_name >myoutput.txt
            - echo $MY_MESSAGE >>myoutput.txt
            - cat myoutput.txt
      - name: ag_step_2
        type: Bash
        configuration:
          runtime:
            type: host        
          affinityGroup: together
          inputSteps:
             - name: ag_step_1
        execution:
          onExecute:
            - cat myoutput.txt
